-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- vim.cmd("colorscheme rose-pine")
-- vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
